export const ADD_ALL_FILTERS = 'ADD_ALL_FILTERS';
export const ADD_ACTIVE_FILTER = 'ADD_ACTIVE_FILTER';
export const REMOVE_ACTIVE_FILTER = 'REMOVE_ACTIVE_FILTER';
export const REMOVE_ACTIVE_FILTERS = 'REMOVE_ACTIVE_FILTERS';
